# Generated by Django 4.2.7 on 2023-11-07 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(8)])),
                ('dv_run', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=30)),
                ('snombre', models.CharField(max_length=30)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(max_length=50)),
                ('correoelectronico', models.CharField(db_column='correoElectronico', max_length=65)),
                ('telefono', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('nombreusuario', models.CharField(db_column='nombreUsuario', max_length=20)),
                ('contrasena', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('calificacionpromedio', models.DecimalField(db_column='calificacionPromedio', decimal_places=1, max_digits=2)),
                ('escliente', models.BooleanField(db_column='esCliente', default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dueno',
                'managed': False,
            },
        ),
    ]
