# Generated by Django 4.2.7 on 2023-11-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dueno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dueno',
            options={'managed': False, 'verbose_name': 'Dueño', 'verbose_name_plural': 'Dueños'},
        ),
    ]
