# Generated by Django 4.2.7 on 2023-12-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dueno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dueno',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
