# Generated by Django 4.2.2 on 2023-11-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dueno', '0002_alter_dueno_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntointeres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(max_length=255)),
                ('longitud', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Punto de Interes',
                'verbose_name_plural': 'Punto de Intereses',
                'db_table': 'puntointeres',
                'managed': False,
            },
        ),
    ]
