# Generated by Django 4.2.7 on 2023-12-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('imagen_cliente', models.ImageField(blank=True, null=True, upload_to='imagenCliente/', verbose_name='Imagen')),
                ('calificacion_promedio_cliente', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Calificacion Promedio del Cliente')),
            ],
            options={
                'abstract': False,
            },
            bases=('usuario.usuario',),
        ),
    ]
