# Generated by Django 4.2.7 on 2023-12-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('transaccion_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.IntegerField()),
                ('dv_run', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('snombre', models.CharField(max_length=30, verbose_name='Segundo Nombre')),
                ('appaterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apmaterno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('correoelectronico', models.CharField(db_column='correoElectronico', max_length=65, verbose_name='Correo Electronico')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('nombreusuario', models.CharField(db_column='nombreUsuario', max_length=20, verbose_name='Nombre de Usuario')),
                ('contrasena', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('calificacionpromedio', models.DecimalField(blank=True, db_column='calificacionPromedio', decimal_places=1, max_digits=2, null=True, verbose_name='Calificacion Promedio')),
                ('activo', models.BooleanField(default=True, verbose_name='Cliente Activo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotoCliente/', verbose_name='Imagen del Cliente')),
                ('id_banco', models.ForeignKey(db_column='id_banco', on_delete=django.db.models.deletion.DO_NOTHING, to='transaccion_pago.banco', verbose_name='Banco')),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.comuna', verbose_name='Comuna')),
                ('id_tarjetacredito', models.ForeignKey(db_column='id_tarjetaCredito', on_delete=django.db.models.deletion.DO_NOTHING, to='transaccion_pago.tarjetacredito', verbose_name='Tarjeta de Credito')),
            ],
        ),
    ]
