# Generated by Django 4.2.7 on 2023-11-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
