# Generated by Django 4.2.7 on 2023-12-09 06:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencia'], [3, 'Felicitaciones']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('run', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='Run')),
                ('dv_run', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[1-9K]$')], verbose_name='Digito Verificador')),
                ('nombre', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')], verbose_name='Nombre')),
                ('appaterno', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')], verbose_name='Apellido Paterno')),
                ('apmaterno', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')], verbose_name='Apellido Materno')),
                ('nombre_usuario', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9@]+$')], verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('telefono', models.IntegerField(unique=True, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=70, verbose_name='Direccion')),
                ('vehiculos', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Vehiculos')),
                ('tarjetas_credito', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Tarjetas de Credito')),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.comuna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('id_region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.region', verbose_name='Region')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_provincia',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.provincia', verbose_name='Provincia'),
        ),
    ]
