# Generated by Django 4.2.7 on 2023-12-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duenoprofile',
            name='estacionamientos',
        ),
    ]
