# Generated by Django 4.2.7 on 2023-12-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='dv_run',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='rut',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='duenoprofile',
            name='dv_run',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='duenoprofile',
            name='rut',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='duenoprofile',
            name='estacionamiento',
            field=models.IntegerField(default=0),
        ),
    ]
