# Generated by Django 4.2.7 on 2023-12-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_duenoprofile_estacionamientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteprofile',
            name='vehiculos',
        ),
        migrations.RemoveField(
            model_name='duenoprofile',
            name='vehiculos',
        ),
    ]
