# Generated by Django 4.2.7 on 2023-12-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_clienteprofile_vehiculos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteprofile',
            name='calificacion_promedio_cliente',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Calificacion Promedio del Cliente'),
        ),
        migrations.AlterField(
            model_name='duenoprofile',
            name='calificacion_promedio_dueno',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, verbose_name='Calificacion Promedio del Dueño'),
        ),
    ]
