# Generated by Django 4.2.7 on 2023-12-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocalizacion', '0001_initial'),
        ('cliente', '0001_initial'),
        ('dueno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotoCasilla/', verbose_name='Imagen de la Casilla del Estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=False, verbose_name='Estado Estacionamiento')),
                ('tarifahora', models.IntegerField(db_column='tarifaHora', verbose_name='Tarifa por Hora')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotoEstacionamiento/', verbose_name='Imagen del Estacionamiento')),
                ('id_dueno', models.ForeignKey(db_column='id_dueno', on_delete=django.db.models.deletion.DO_NOTHING, to='dueno.dueno', verbose_name='Dueño')),
                ('id_puntoInteres', models.ForeignKey(db_column='id_puntointeres', on_delete=django.db.models.deletion.DO_NOTHING, to='geolocalizacion.puntointeres', verbose_name='Punto de Interes')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('estacionado', models.BooleanField(default=False, verbose_name='Vehiculo Estacionado')),
            ],
        ),
        migrations.CreateModel(
            name='EstacionamientoCasilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disponible', models.BooleanField(default=True)),
                ('id_casilla', models.ForeignKey(db_column='id_casilla', on_delete=django.db.models.deletion.DO_NOTHING, to='estacionamiento.casilla')),
                ('id_estacionamiento', models.ForeignKey(db_column='id_estacionamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='estacionamiento.estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='DuenoVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_dueno', models.ForeignKey(db_column='id_dueno', on_delete=django.db.models.deletion.DO_NOTHING, to='dueno.dueno', verbose_name='Dueño')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='estacionamiento.vehiculo', verbose_name='Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente', verbose_name='Cliente')),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='estacionamiento.vehiculo', verbose_name='Vehiculo')),
            ],
        ),
    ]
