# Generated by Django 4.2.7 on 2023-12-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=False, verbose_name='Estado Estacionamiento')),
                ('tarifahora', models.IntegerField(db_column='tarifaHora', verbose_name='Tarifa por Hora')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotoEstacionamiento/', verbose_name='Imagen del Estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('modelo', models.CharField(max_length=255)),
                ('estacionado', models.BooleanField(default=False, verbose_name='Vehiculo Estacionado')),
                ('id_marca', models.ForeignKey(db_column='id_marca', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='estacionamiento.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Casilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('casilla', models.CharField(max_length=30)),
                ('disponible', models.BooleanField(default=True)),
                ('id_estacionamiento', models.ForeignKey(db_column='id_estacionamiento', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='estacionamiento.estacionamiento')),
            ],
        ),
    ]
