# Generated by Django 4.2.7 on 2023-11-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuenoVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Vehiculo/Dueño',
                'verbose_name_plural': 'Vehiculos/Dueño',
                'db_table': 'dueno_vehiculo',
                'managed': False,
            },
        ),
    ]
