# Generated by Django 4.2.7 on 2023-12-15 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacionamiento', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geolocalizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='id_dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.duenoprofile'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='id_puntoInteres',
            field=models.ForeignKey(db_column='id_puntointeres', on_delete=django.db.models.deletion.CASCADE, to='geolocalizacion.puntointeres', verbose_name='Punto de Interes'),
        ),
        migrations.AddField(
            model_name='casilla',
            name='id_estacionamiento',
            field=models.ForeignKey(db_column='id_estacionamiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.estacionamiento', verbose_name='Estacionamientos'),
        ),
    ]
