# Generated by Django 4.2.7 on 2023-12-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalizacion', '0001_initial'),
        ('estacionamiento', '0002_estacionamiento_id_puntointeres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='id_puntoInteres',
            field=models.ForeignKey(db_column='id_puntointeres', on_delete=django.db.models.deletion.DO_NOTHING, to='geolocalizacion.puntointeres', verbose_name='Punto de Interes'),
        ),
    ]
