# Generated by Django 4.2.7 on 2023-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0002_duenovehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Vehiculo/Cliente',
                'verbose_name_plural': 'Vehiculos/Cliente',
                'db_table': 'cliente_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=False)),
                ('tarifahora', models.IntegerField(db_column='tarifaHora')),
                ('coordenadasgps', models.CharField(db_column='coordenadasGPS', max_length=255)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'estacionamiento',
                'managed': False,
            },
        ),
    ]
