# Generated by Django 4.2.7 on 2023-11-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0003_clientevehiculo_estacionamiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacionamiento',
            options={'managed': False, 'verbose_name': 'Estacionamiento', 'verbose_name_plural': 'Estacionamientos'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'managed': False, 'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
    ]
