# Generated by Django 4.2.7 on 2023-12-12 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0003_alter_estacionamiento_id_puntointeres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casilla',
            name='id_estacionamiento',
            field=models.ForeignKey(db_column='id_estacionamiento', default=None, on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.estacionamiento'),
        ),
    ]
