# Generated by Django 4.2.7 on 2023-11-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0004_alter_estacionamiento_options_alter_vehiculo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.CharField(max_length=30)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Casilla',
                'verbose_name_plural': 'Casillas',
                'db_table': 'casilla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstacionamientoCasilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Estacionamiento/Casilla',
                'verbose_name_plural': 'Estacionamientos/Casillas',
                'db_table': 'estacionamiento_casilla',
                'managed': False,
            },
        ),
    ]
