# Generated by Django 4.2.7 on 2023-12-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0004_alter_casilla_id_estacionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casilla',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
