# Generated by Django 4.2.7 on 2023-12-12 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0006_alter_casilla_id_estacionamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casilla',
            name='id_estacionamiento',
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='id_casillas',
            field=models.ForeignKey(db_column='id_casillas', null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.casilla', verbose_name='Casillas'),
        ),
    ]
