# Generated by Django 4.2.7 on 2023-12-12 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0007_remove_casilla_id_estacionamiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='id_casillas',
        ),
        migrations.AddField(
            model_name='casilla',
            name='id_estacionamiento',
            field=models.ForeignKey(db_column='id_estacionamientos', null=True, on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.estacionamiento', verbose_name='Estacionamientos'),
        ),
    ]
