# Generated by Django 4.2.7 on 2023-11-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horainicio', models.DateTimeField(db_column='horaInicio', verbose_name='Hora de Inicio')),
                ('horafin', models.DateTimeField(db_column='horaFin', verbose_name='Hora de Fin')),
                ('preciototal', models.IntegerField(db_column='precioTotal', verbose_name='Precio Total')),
                ('calificacioncliente', models.DecimalField(blank=True, db_column='calificacionCliente', decimal_places=1, max_digits=2, null=True, verbose_name='Calificacion para el Cliente')),
                ('calificaciondueno', models.DecimalField(blank=True, db_column='calificacionDueno', decimal_places=1, max_digits=2, null=True, verbose_name='Calificacion para el Dueño')),
            ],
            options={
                'verbose_name': 'Arriendo',
                'verbose_name_plural': 'Arriendos',
                'db_table': 'arriendo',
                'managed': False,
            },
        ),
    ]
