# Generated by Django 4.2.7 on 2023-12-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dueno', '0001_initial'),
        ('cliente', '0001_initial'),
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horainicio', models.DateTimeField(db_column='horaInicio', verbose_name='Hora de Inicio')),
                ('horafin', models.DateTimeField(db_column='horaFin', verbose_name='Hora de Fin')),
                ('preciototal', models.IntegerField(db_column='precioTotal', verbose_name='Precio Total')),
                ('calificacioncliente', models.DecimalField(blank=True, db_column='calificacionCliente', decimal_places=1, max_digits=2, null=True, verbose_name='Calificacion para el Cliente')),
                ('calificaciondueno', models.DecimalField(blank=True, db_column='calificacionDueno', decimal_places=1, max_digits=2, null=True, verbose_name='Calificacion para el Dueño')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente', verbose_name='Cliente')),
                ('id_dueno', models.ForeignKey(db_column='id_dueno', on_delete=django.db.models.deletion.DO_NOTHING, to='dueno.dueno', verbose_name='Dueño')),
                ('id_estacionamiento', models.ForeignKey(db_column='id_estacionamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='estacionamiento.estacionamiento', verbose_name='Estacionamiento')),
            ],
        ),
    ]
