# Generated by Django 4.2.7 on 2023-12-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arriendo', '0001_initial'),
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='id_estacionamiento',
            field=models.ForeignKey(db_column='id_estacionamiento', on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.estacionamiento', verbose_name='Estacionamiento'),
        ),
    ]
