# Generated by Django 4.2.7 on 2023-12-15 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arriendo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
