# Generated by Django 4.2.7 on 2023-12-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_clienteprofile_calificacion_promedio_cliente_and_more'),
        ('arriendo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='is_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.clienteprofile'),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
