# Generated by Django 4.2.7 on 2023-12-15 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arriendo', '0003_remove_arriendo_id_cliente_arriendo_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
