# Generated by Django 4.2.7 on 2023-12-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0003_arriendo_is_cliente_alter_arriendo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='is_cliente',
            new_name='id_cliente',
        ),
    ]
