# Generated by Django 4.2.7 on 2023-12-09 06:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('id_usuario_entrega', models.ForeignKey(db_column='id_usuario_entrega', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calificaciones_entregadas', to='usuario.usuario', verbose_name='ID del que entrega la calificacion')),
                ('id_usuario_recibe', models.ForeignKey(db_column='id_usuario_recibe', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calificaciones_recibidas', to='usuario.usuario', verbose_name='ID del usuario que recibe la calificacion')),
            ],
        ),
    ]
