# Generated by Django 4.2.7 on 2023-12-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('calificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='id_usuario_entrega',
            field=models.ForeignKey(db_column='id_usuario_entrega', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calificaciones_entregadas', to='usuario.usuario', verbose_name='ID del que entrega la calificacion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='id_usuario_recibe',
            field=models.ForeignKey(db_column='id_usuario_recibe', on_delete=django.db.models.deletion.DO_NOTHING, related_name='calificaciones_recibidas', to='usuario.usuario', verbose_name='ID del usuario que recibe la calificacion'),
        ),
    ]
