# Generated by Django 4.2.7 on 2023-11-07 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetacredito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(19)])),
                ('fechavencimiento', models.DateField(db_column='fechaVencimiento')),
                ('cvv', models.IntegerField(db_column='CVV', validators=[django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'db_table': 'tarjetacredito',
                'managed': False,
            },
        ),
    ]
