# Generated by Django 4.2.7 on 2023-11-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banco',
            table='banco',
        ),
    ]
