# Generated by Django 4.2.7 on 2023-11-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion_pago', '0002_alter_banco_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'managed': False, 'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='tarjetacredito',
            options={'managed': False, 'verbose_name': 'Tarjeta de Credito', 'verbose_name_plural': 'Tarjetas de Credito'},
        ),
    ]
